go:
    # Whenever the Go version is updated here, .travis.yml and
    # .circle/config.yml should also be updated.
    version: 1.12
repository:
    path: github.com/dnxware/dnxware
build:
    binaries:
        - name: dnxware
          path: ./cmd/dnxware
        - name: promtool
          path: ./cmd/promtool
    flags: -mod=vendor -a -tags netgo
    ldflags: |
        -X github.com/dnxware/common/version.Version={{.Version}}
        -X github.com/dnxware/common/version.Revision={{.Revision}}
        -X github.com/dnxware/common/version.Branch={{.Branch}}
        -X github.com/dnxware/common/version.BuildUser={{user}}@{{host}}
        -X github.com/dnxware/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - consoles
        - console_libraries
        - documentation/examples/dnxware.yml
        - LICENSE
        - NOTICE
crossbuild:
    platforms:
        - linux/amd64
        - linux/386
        - darwin/amd64
        - darwin/386
        - windows/amd64
        - windows/386
        - freebsd/amd64
        - freebsd/386
        - openbsd/amd64
        - openbsd/386
        - netbsd/amd64
        - netbsd/386
        - dragonfly/amd64
        - linux/arm
        - linux/arm64
        - freebsd/arm
        # Temporarily deactivated as golang.org/x/sys does not have syscalls
        # implemented for that os/platform combination.
        #- openbsd/arm
        #- linux/mips64
        #- linux/mips64le
        - netbsd/arm
        - linux/ppc64
        - linux/ppc64le
        - linux/s390x

